apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valkey-cluster.fullname" . }}-config
  labels:
    {{- include "valkey-cluster.labels" . | nindent 4 }}
data:
  valkey.conf: |-
{{ include "valkey-cluster.generateConfig" . | indent 4 }}
