apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valkey.fullname" . }}-config
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
data:
  valkey.conf: |-
{{ include "valkey.generateConfig" . | indent 4 }}
