apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valkey-cluster.fullname" . }}-readiness-script
  namespace: {{ .Release.Namespace | quote }}
data:
  ping_readiness_local.sh: |-
{{ .Files.Get "scripts/readiness-probe.sh" | indent 4 }}