apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey-cluster.fullname" . }}-headless
  namespace: {{ include "valkey-cluster.names.namespace" . }}
  labels:
    {{- include "valkey-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.containerPorts.valkey }}
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: {{ .Values.containerPorts.bus }}
      targetPort: bus
      protocol: TCP
      name: bus
  selector:
    {{- include "valkey-cluster.selectorLabels" . | nindent 4 }}
