apiVersion: v2
name: valkey-operator
description: A Helm chart for the Valkey Operator
type: application
version: 0.2.3
appVersion: "v0.2.0"
kubeVersion: ">=1.20.0-0"
home: https://valkey.io/valkey-helm/
sources:
  - https://github.com/valkey-io/valkey-operator.git
  - https://valkey.io
maintainers:
  - name: daanvinken
    url: https://github.com/daanvinken
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
