apiVersion: valkey.io/v1alpha1
kind: ValkeyCluster
metadata:
  name: {{ include "valkey-resources.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey-resources.labels" . | nindent 4 }}
    {{- with .Values.cluster.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  {{- with .Values.cluster.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- tpl (toYaml .Values.cluster.spec) . | nindent 2 }}
