{{- if and .Values.rbac.create .Values.metrics.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "valkey-operator.fullname" . }}-metrics-reader
  labels:
    {{- include "valkey-operator.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
{{- end }}
