{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}-auth
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.auth.password | quote }}
{{- end }}
