{{- if and .Values.haproxy.enabled .Values.haproxy.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "valkey.fullname" . }}-haproxy
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: haproxy
spec:
  {{- if .Values.haproxy.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.haproxy.podDisruptionBudget.minAvailable }}
  {{- else if .Values.haproxy.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.haproxy.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "valkey.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: haproxy
  {{- with .Values.haproxy.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
{{- end }}
