{{- with .Values.networkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "valkey.fullname" $ }}
  labels:
    {{- include "renderTplValues" (dict "value" .labels "indent" 4 "root" $ ) }}
  annotations:
    {{- include "renderTplValues" (dict "value" .annotations "indent" 4 "root" $ ) }}
spec:
  podSelector:
    matchLabels:
      {{- include "valkey.selectorLabels" $ | nindent 6 }}
  policyTypes:
  {{- if .ingress }}
    - Ingress
  {{- end }}
  {{- if .egress }}
    - Egress
  {{- end }}
  ingress:
    {{- include "renderTplValues" (dict "value" .ingress "indent" 4 "root" $ ) }}
  egress:
    {{- include "renderTplValues" (dict "value" .egress "indent" 4 "root" $ ) }}
{{- end }}
