{{- if or (and .Values.auth.enabled (or (include "valkey.hasInlinePasswords" . | eq "true") .Values.auth.aclConfig)) (and .Values.replica.enabled .Values.replica.sentinel.enabled .Values.replica.sentinel.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}-auth
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.replica.enabled .Values.replica.sentinel.enabled .Values.replica.sentinel.password }}
  sentinel-password: {{ .Values.replica.sentinel.password | b64enc }}
  {{- end }}
  {{- if .Values.auth.enabled }}
  {{- range $username, $user := .Values.auth.aclUsers }}
    {{- if $user.password }}
  {{ $username }}-password: {{ $user.password | b64enc }}
    {{- end }}
  {{- end }}
  {{- if .Values.auth.aclConfig }}
  aclConfig: {{ .Values.auth.aclConfig | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
