{{- if and .Values.replica.enabled .Values.replica.sentinel.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}-sentinel-headless
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: sentinel
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: sentinel
      port: {{ .Values.replica.sentinel.port }}
      targetPort: sentinel
      protocol: TCP
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sentinel
{{- end }}
