{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled .Values.metrics.service.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: valkey
    app.kubernetes.io/component: service-monitor
    {{- include "renderTplValues" (dict "value" .Values.metrics.serviceMonitor.extraLabels "indent" 4 "root" $ ) }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: {{ .Values.metrics.serviceMonitor.port }}
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ . }}
      {{- end }}
      relabelings:
        {{- include "renderTplValues" (dict "value" .Values.metrics.serviceMonitor.relabelings "indent" 6 "root" $ ) }}
      metricRelabelings:
        {{- include "renderTplValues" (dict "value" .Values.metrics.serviceMonitor.metricRelabelings "indent" 6 "root" $ ) }}
  podTargetLabels:
    {{- include "renderTplValues" (dict "value" .Values.metrics.serviceMonitor.podTargetLabels "indent" 4 "root" $ ) }}
  {{- with .Values.metrics.serviceMonitor.sampleLimit }}
  sampleLimit: {{ . }}
  {{- end }}
  {{- with .Values.metrics.serviceMonitor.targetLimit }}
  targetLimit: {{ . }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "valkey.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
{{- end }}
