{{- if .Values.replica.enabled }}
{{- include "valkey.validateAuthConfig" . }}
{{- include "valkey.validateReplicaPersistence" . }}
{{- include "valkey.validateReplicaAuth" . }}
{{- include "valkey.validateSentinelConfig" . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  {{- with .Values.workloadAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "valkey.fullname" . }}-headless
  replicas: {{ add (int .Values.replica.replicas) 1 }}
  podManagementPolicy: OrderedReady
  {{- if .Values.replica.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    {{- toYaml .Values.replica.persistentVolumeClaimRetentionPolicy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "valkey.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: valkey-data
    spec:
      accessModes: {{ toYaml .Values.replica.persistence.accessModes | nindent 8 }}
      {{- if .Values.replica.persistence.storageClass }}
      storageClassName: {{ .Values.replica.persistence.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.replica.persistence.size | quote }}
  template:
    {{- include "valkey.podTemplate" . | nindent 4 }}
{{- end }}
