{{- if .Values.replica.enabled }}
{{- include "valkey.validateAuthConfig" . }}
{{- include "valkey.validateReplicaPersistence" . }}
{{- include "valkey.validateReplicaAuth" . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "valkey.fullname" . }}-headless
  replicas: {{ add (int .Values.replica.replicas) 1 }}
  podManagementPolicy: OrderedReady
  {{- if .Values.replica.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    {{- toYaml .Values.replica.persistentVolumeClaimRetentionPolicy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "valkey.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
  - metadata:
      name: valkey-data
    spec:
      accessModes: {{- include "renderTplValues" (dict "value" .Values.replica.persistence.accessModes "indent" 8 "root" $ ) }}
      {{- if .Values.replica.persistence.storageClass }}
      storageClassName: {{ .Values.replica.persistence.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.replica.persistence.size | quote }}
  template:
    metadata:
      labels:
        {{- include "valkey.selectorLabels" . | nindent 8 }}
        {{- include "renderTplValues" (dict "value" .Values.commonLabels "indent" 8 "root" $ ) }}
        {{- include "renderTplValues" (dict "value" .Values.podLabels "indent" 8 "root" $ ) }}
      annotations:
        {{- include "renderTplValues" (dict "value" .Values.podAnnotations "indent" 8 "root" $ ) }}
        checksum/initconfig: {{ include (print $.Template.BasePath "/init_config.yaml") . | sha256sum | trunc 32 | quote }}
        {{- if .Values.valkeyConfig }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | trunc 32 | quote }}
        {{- end }}
    spec:
      {{- (include "valkey.imagePullSecrets" .) | nindent 6 }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      serviceAccountName: {{ include "valkey.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      securityContext:
        {{- include "renderTplValues" (dict "value" .Values.podSecurityContext "indent" 8 "root" $ ) }}
      initContainers:
        - name: {{ include "valkey.fullname" . }}-init
          image: {{ include "valkey.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- include "renderTplValues" (dict "value" .Values.securityContext "indent" 12 "root" $ ) }}
          command: [ "/scripts/init.sh" ]
          env:
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          volumeMounts:
            - name: valkey-data
              mountPath: /data
            - name: scripts
              mountPath: /scripts
            {{- if .Values.valkeyConfig }}
            - name: valkey-config
              mountPath: /usr/local/etc/valkey/valkey.conf
              subPath: valkey.conf
            {{- end }}
            {{- if .Values.extraSecretValkeyConfigs }}
            - name: extravalkeyconfigs-volume
              mountPath: /extravalkeyconfigs
            {{- end }}
            {{- if .Values.auth.enabled }}
            - name: valkey-acl
              mountPath: /etc/valkey
            {{- if .Values.auth.usersExistingSecret }}
            - name: valkey-users-secret
              mountPath: /valkey-users-secret
              readOnly: true
            {{- end }}
            {{- if or (include "valkey.hasInlinePasswords" . | eq "true") .Values.auth.aclConfig }}
            - name: valkey-auth-secret
              mountPath: /valkey-auth-secret
              readOnly: true
            {{- end }}
            {{- end }}
          resources:
            {{- include "renderTplValues" (dict "value" .Values.initResources "indent" 12 "root" $ ) }}
      {{- include "renderTplValues" (dict "value" .Values.extraInitContainers "indent" 8 "root" $ ) }}
      containers:
        - name: {{ include "valkey.fullname" . }}
          image: {{ include "valkey.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "valkey-server" ]
          args: [ "/data/conf/valkey.conf" ]
          securityContext:
            {{- include "renderTplValues" (dict "value" .Values.securityContext "indent" 12 "root" $ ) }}
          env:
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            {{- range $key, $env := .Values.env }}
              {{- if $env.enabled }}
            - name: {{ $key }}
              value: "{{ $env.value }}"
              {{- end }}
            {{- end }}
            - name: VALKEY_LOGLEVEL
              value: "{{ .Values.valkeyLogLevel }}"
          ports:
            - name: tcp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          startupProbe:
            exec:
              {{- if .Values.tls.enabled }}
              command: [ "sh", "-c", "valkey-cli --cacert /tls/{{ .Values.tls.caPublicKey }} --tls ping" ]
              {{- else }}
              command: [ "sh", "-c", "valkey-cli ping" ]
              {{- end }}
          livenessProbe:
            exec:
              {{- if .Values.tls.enabled }}
              command: [ "sh", "-c", "valkey-cli --cacert /tls/{{ .Values.tls.caPublicKey }} --tls ping" ]
              {{- else }}
              command: [ "sh", "-c", "valkey-cli ping" ]
              {{- end }}
          resources:
            {{- include "renderTplValues" (dict "value" .Values.resources "indent" 12 "root" $ ) }}
          volumeMounts:
            - name: valkey-data
              mountPath: /data
            {{- if .Values.tls.enabled }}
            - name: {{ include "valkey.fullname" . }}-tls
              mountPath: /tls
            {{- end }}
            {{- if .Values.auth.enabled }}
            - name: valkey-acl
              mountPath: /etc/valkey
            {{- end }}
            {{- range $secret := .Values.extraValkeySecrets }}
            - name: {{ $secret.name }}-valkey
              mountPath: {{ $secret.mountPath }}
            {{- end }}
            {{- range $config := .Values.extraValkeyConfigs }}
            - name: {{ $config.name }}-valkey
              mountPath: {{ $config.mountPath }}
            {{- end }}
            {{- include "renderTplValues" (dict "value" .Values.extraVolumeMounts "indent" 12 "root" $ ) }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: {{ include "valkey.metrics.exporter.image" . }}
          imagePullPolicy: {{ .Values.metrics.exporter.image.pullPolicy | quote }}
          securityContext:
            {{- include "renderTplValues" (dict "value" .Values.metrics.exporter.securityContext "indent" 12 "root" $ ) }}
          command:
            {{- include "renderTplValues" (dict "value" .Values.metrics.exporter.command "indent" 12 "root" $ ) }}
          args:
            {{- include "renderTplValues" (dict "value" .Values.metrics.exporter.args "indent" 12 "root" $ ) }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.exporter.port }}
          startupProbe:
            tcpSocket:
              port: metrics
          livenessProbe:
            tcpSocket:
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            {{- include "renderTplValues" (dict "value" .Values.metrics.exporter.resources "indent" 12 "root" $ ) }}
          volumeMounts:
            {{- include "renderTplValues" (dict "value" .Values.metrics.exporter.extraVolumeMounts "indent" 12 "root" $ ) }}
          env:
            - name: REDIS_ALIAS
              value: {{ include "valkey.fullname" . }}
            {{- range $key, $val := .Values.metrics.exporter.extraEnvs }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
        {{- end }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "valkey.fullname" . }}-init-scripts
            defaultMode: 0555
        {{- if .Values.auth.enabled }}
        - name: valkey-acl
          emptyDir:
            medium: Memory
        {{- end }}
        {{- if .Values.valkeyConfig }}
        - name: valkey-config
          configMap:
            name: {{ include "valkey.fullname" . }}-config
        {{- end }}
        {{- range .Values.extraValkeySecrets }}
        - name: {{ .name }}-valkey
          secret:
            secretName: {{ .name }}
            defaultMode: {{ .defaultMode | default 0440 }}
        {{- end }}
        {{- if .Values.tls.enabled }}
        - name: {{ include "valkey.fullname" . }}-tls
          secret:
            secretName: {{ required "An existing secret is required to enable TLS" .Values.tls.existingSecret }}
            defaultMode: 0400
        {{- end }}
        {{- range .Values.extraValkeyConfigs }}
        - name: {{ .name }}-valkey
          configMap:
            name: {{ .name }}
            defaultMode: {{ .defaultMode | default 0440 }}
        {{- end }}
        {{- if .Values.metrics.enabled }}
        {{- range .Values.metrics.exporter.extraExporterSecrets }}
        - name: {{ .name }}-exporter
          secret:
            secretName: {{ .name }}
            defaultMode: {{ .defaultMode | default 0440 }}
        {{- end }}
        {{- end }}
        {{- if .Values.auth.enabled }}
        {{- if .Values.auth.usersExistingSecret }}
        - name: valkey-users-secret
          secret:
            secretName: {{ .Values.auth.usersExistingSecret }}
            defaultMode: 0400
        {{- end }}
        {{- if or (include "valkey.hasInlinePasswords" . | eq "true") .Values.auth.aclConfig }}
        - name: valkey-auth-secret
          secret:
            secretName: {{ include "valkey.fullname" . }}-auth
            defaultMode: 0400
        {{- end }}
        {{- end }}
        {{- include "renderTplValues" (dict "value" .Values.extraVolumes "indent" 8 "root" $ ) }}
      nodeSelector:
        {{- include "renderTplValues" (dict "value" .Values.nodeSelector "indent" 8 "root" $ ) }}
      affinity:
        {{- include "renderTplValues" (dict "value" .Values.affinity "indent" 8 "root" $ ) }}
      topologySpreadConstraints:
        {{- include "renderTplValues" (dict "value" .Values.topologySpreadConstraints "indent" 8 "root" $ ) }}
      tolerations:
        {{- include "renderTplValues" (dict "value" .Values.tolerations "indent" 8 "root" $ ) }}
{{- end }}
